dist: trusty

sudo: required

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - python --version

install:
  - travis_retry make install-ci

before_script:
  - pip freeze

script:
  - make test

after_script:
  - travis_retry pip list --outdated

after_success:
  - make lint

cache:
  pip: true

notifications:
  email: false

  slack: oceanio:4CG2OxeU91DXAXKX5VsHeD8l
